name: Running Code Coverage
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10'
    steps:
    - uses: checkout@v3
      with:
        fetch-depth: '2'
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate Report
      run: |
        pip install coverage mypy
        mypy tailparse
        coverage run -m unittest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      ignore:
        - "*/tests/*"
